### ISSUE TITLE
Strip shortcodes

### ISSUE THREAD

**Issue by bsides** [discourse/wp-discourse#150]
Can we have the post with shortcodes stripped? Right now I'm using some visual content editors and they are full of custom shortcodes. Posting them to Discourse looks really silly, unfortunatelly.

Thank you in advance.

**Comment by pixeldynamo** [comment]
With many of us using Markdown in our posts how can the plugin differentiate between blocks of markdown and shortcodes?

**Comment by bsides** [comment]
Could we at least have this option to remove any other [regex] from the code? How about that? :+1:

**Comment by pixeldynamo** [comment]
That's my point, markdown uses [] as do shortcodes, including the old-style native WP embeds. There's already a collision with the likes of [video] at WP (which Discourse handles correctly).

**Comment by bsides** [comment]
How is the product of a shortcut being the shortcut? Do you mean the parse should be handled by the plugin before going to post_content_filtered?

**Comment by pixeldynamo** [comment]
No, I mean that the post information that the plugin looks at doesn't contain shortcodes. At that point they've already been converted into their relevant HTML.

**Comment by bsides** [comment]
Ahhhh I see. What I mentioned earlier wasnt to just strip out shortcodes but any regex chosen by the user. Of course that's a little advanced but would solve that in case I choose to strip everything and leave it text only, no?

**Comment by pixeldynamo** [comment]
What exactly are you seeing appear in Discourse? Our posts, which include shortcode generated content, are posted as a plain text version of the content, not the codes of HTML that they produce.

**Comment by bsides** [comment]
Well I'm seeing the content with the shortcodes on it, like ```[aesop gallery=1]``` inside the text or ```[onebox url="theurl"]```

**Comment by scossar** [comment]
I spent some time looking at how shortcodes can interact with the plugin. It seems that there is no solution that will work for all cases. The plugin applies a WordPress `filter` to the content that is published to Discourse. The best solution for dealing with shortcodes seems to be to do it on a theme-by-theme bases by hooking into this filter. The filter is called `wp_discourse_excerpt` (it is applied even if you are using the full-post content.)

Use only one of these functions in your theme's `functions.php` file. The 'testeleven_' prefix is just something I use in my own work to avoid naming collisions. Replace it with something suitable.

this function will strip the shortcodes from the content:

```php
// Strips any shortcodes from the post content. If  theme is wrapping content between
// opening and closing shortcodes, that content will be removed as well.
add_filter( 'wp_discourse_excerpt', 'testeleven_strip_shortcodes' );
function testeleven_strip_shortcodes( $excerpt ) {
  $excerpt = strip_shortcodes( $excerpt );

  return $excerpt;
}
```

this function will 'do' any shortcodes that are in the content:
```php
// Searches the content for shortcodes and filter shortcodes through their hooks.
add_filter( 'wp_discourse_excerpt', 'testeleven_do_shortcodes' );
function testeleven_do_shortcodes( $excerpt ) {
  $excerpt = do_shortcode( $excerpt );

  return $excerpt;
}
```

this function will remove any content that looks like a shortcode. It would be possible to get much more specific with the regular expression that is being used:
```php
// Removes anything that looks like a shortcode. This will remove anything in the post that
// occurs inside of brackets `[...]`.
add_filter( 'wp_discourse_excerpt', 'testeleven_remove_shortcodes' );
function testeleven_remove_shortcodes( $excerpt ) {
  $excerpt = preg_replace( '/\[.*\]/', '', $excerpt );

  return $excerpt;
}
```

If you are going to try any of these I would suggest you update your version of the plugin to the latest. I found a bug while working on this that can make a post so that it can't be edited. I pushed a fix for that just now.
