### ISSUE TITLE
Redirect to woocommerce login

### ISSUE THREAD

**Issue by bk1285** [discourse/wp-discourse#173]
First: Thank you very much for this awesome plugin!

Second: I'd like to expand it: I have a wordpress install, where users login with woocommerce instead the default wp-login page: The login-site is therefore example.com/my-account

Editing the url to redirect users to example.com/my-account 
https://github.com/discourse/wp-discourse/blob/master/lib/discourse.php#L153-167

...ends up in an endless loop of redirects with an increasing length of the url.

example.com/my-account/?sso=abc....xyz%0B&sig=abc...xyz
example.com/my-account/my-account/?sso=abc....xyz%0B&sig=abc...xyz
example.com/my-account/my-account/my-account/?sso=abc....xyz%0B&sig=abc...xyz
example.com/my-account/my-account/my-account/my-account/?sso=abc....xyz%0B&sig=abc...xyz
...

Does anybody have a hint, how to handle this? Any help appreciated!

Best!
Bernd

**Comment by shawaj** [comment]
I would be interested in this too. Any progress @bk1285 ?

**Comment by bk1285** [comment]
Sorry to tell you: No progress...

**Comment by scossar** [comment]
Try setting the Discourse `sso url` to `http://example.com/my-account` and adding something like this to your theme's `functions.php` file:

```php
add_filter( 'login_url', 't11_login_url', 10, 2 );
function t11_login_url( $login_url, $redirect ) {
	$woo_url = home_url( '/my-account/' );

	if ( !empty( $redirect ) ) {
		$woo_url = add_query_arg( 'redirect_to', urlencode( $redirect ), $woo_url );
	}

	return $woo_url;
}

add_action( 'woocommerce_login_form_end', 't11_set_redirect' );
function t11_set_redirect() {
	$redirect = $_GET['redirect_to'];
	echo '<input type="hidden" name="redirect" value="' . $redirect . '">';
}	
```

**Comment by bk1285** [comment]
Looks great! I'll give it a try! :)

**Comment by scossar** [comment]
There is some support for WooCommerce built into the plugin now. With the latest version of the plugin, all you need to to to use it is enter  `/my-account` into the Discourse `Path to your login page setting.`

See https://github.com/discourse/wp-discourse/wiki/Tips-and-Tricks#use-the-woocommerce-login-page

**Comment by bk1285** [comment]
Great work, @scossar! Works perfectly now! Thanks a lot! :+1:

**Comment by scossar** [comment]
For the moment, do not include the woocommerce registration forms on your site while you are using the site as the SSO provider for Discourse.

![screenshot 2016-07-08 13 20 44](https://cloud.githubusercontent.com/assets/2975917/16700462/08c0551e-450f-11e6-9cac-fb93f377ef49.png)

Completing the woocommerce registration form automatically logs in the user, without first having them verify their email address. This can lead to all sorts of problems. I'll update the code to deal with this right away.

**Comment by shawaj** [comment]
@scossar - was this fixed yet? Just wondered because we can't really implement it until it has.

But thanks for your hard work on this!!

**Comment by shawaj** [comment]
Also, now you have included the new options - i am guessing the code and info in your may 22nd comment above is no longer necessary?

Thanks

**Comment by shawaj** [comment]
I have also just been testing this and it seems to restrict me from logging in at my-site.com/wp-admin at all and also it seems to not work with the 2-factor authentication plugin that I am using!

Is there a different way we could implement this to avoid these issues?

Thanks

**Comment by scossar** [comment]
Yes, this can be made to work. Can you try it without the 2-factor
authentication plugin? What do you have set as the login page? You need to
set that as the  'Path to your login page' on the wp-discourse settings
page.

I can check this out some more tomorrow if you're having any problems. (If
you're downloading the plugin directly from Github, make sure you are using
the beta branch.)

**Comment by shawaj** [comment]
@scossar - well for our dashboard (when we log in to the site to make changes to things, add products etc) we have to log in at www.site.com/wp-admin however when a customer logs in they have to log in at www.site.com/my-account so we need to have the ability to use the wp-admin login when the login request is not coming from SSO because all of our site admins and staff need to log in here.

I put /my-account in the plugin settings and it does not work to login to either the main site dashboard or at the my-account section. You sign in and it just redirects you to the my-account page. Additionally, the email verification doesn't get sent properly every time and even when it does the link that would usually go to the wp-login.php page just says /my-account and is not linked to anything.

We can't disable the 2-factor I am afraid as this is part of the security of our website. We are using the ithemes security pro plugin for 2-factor.

Running the latest version of the plugin 0.9.4 from wordpress.

**Comment by scossar** [comment]
I've just tested this quickly and everything seems to be working as expected, but it still might not work for what you are trying to do.

The problem is that WordPress doesn't properly verify the user's email address. The WooCommerce registration form logs a newly registered user into WordPress without having them respond to an activation email. Discourse relies on having a validated email address for the user, so this becomes a security concern. The verification email that is being sent out is a partial workaround for the problem, but the only good solution at this point is to not enable registration through WooCommerce.

I would like to be able to test this with the ithemes security pro plugin, but I don't want to buy the plugin to do the tests.

I think integrating WooCommerce and Discourse is a great idea, so I'm still looking for ways to get this to work.

**Comment by shawaj** [comment]
@scossar we have a multi-site license if you want one to play with for testing purposes with ithemes security?

Why does it need validation on the email? To stop bots?

Could the redirects etc not work through a cookie instead of URL queries? Would that make it more versatile?

The problem is - we can't redirect all logins to /my-account - only ones that come through SSO request from the forum.

Really keen to get this working, in fact would be happy to pay for it to work beautifully...just don't have any idea where to start really! And since the main site is a production site I don't really want to start poking around too much and removing plugins as any downtime of the frontend will cause issues for orders etc.

**Comment by scossar** [comment]
A few people are interested in this. I'll try out a different way of doing
it later today or early tomorrow.

**Comment by shawaj** [comment]
Thanks so much, it's much appreciated. I owe you many beers and more :-)

**Comment by scossar** [comment]
In the latest release (0.9.5) if the email can't be verified by WordPress it forces Discourse verify it instead. Hopefully this can work for you.

**Comment by shawaj** [comment]
Great, thanks a lot.

Any easy way to sort the problem of not being able to also use the wp-admin
login for our admins?

And the use of two factor authentication on some accounts?

Thanks

**Comment by scossar** [comment]
> Any easy way to sort the problem of not being able to also use the wp-admin


No I don't think so. If you have disabled the admin bar on your site they
will have to manually enter the url yourdomain.com/wp-admin

 And the use of two factor authentication on some accounts?


That should work. Discourse is still going to force them to authenticate
their email address the first time they log into the forum.
