### ISSUE TITLE
Matching existing Discourse user accounts

### ISSUE THREAD

**Issue by no2pixel** [discourse/wp-discourse#279]
We are merging and existing Discourse forum with an existing WordPress site -- both sites have the same user database, but the discourse installation previously had an SSO provider set up with a separate Django application (same users - they have now been migrated to WordPress). When we set up the WordPress site as an SSO provider, attempting to log-in to the Discourse site results in a "An account could not be registered with the email address" error because, obviously, users already exist with that email address. 

I would expect that the SSO function would check for existing users, and log in as necessary using that existing user, rather than failing because the user exists. 

Is there a workaround to get our WordPress and Discourse sites set up properly with SSO?

**Comment by scossar** [comment]
> I would expect that the SSO function would check for existing users, and log in as necessary using that existing user, rather than failing because the user exists.

Yes, that's how it's supposed to work. If a Discourse user is not yet associated with an external id from an SSO provider, they will be looked up by their email address.

It sounds like the users on your forum are already associated with an external id from your previous setup. The WP Discourse plugin uses the WordPress user's id as the SSO external id. In your previous setup, how were you generating the external id? Is it the WordPress user id, or something else?

**Comment by no2pixel** [comment]
The previous setup used a different user management (through a Django app, these users were imported from). The users were imported from there, but the numeric ID values were not copied directly (due to some users already existing on the Wordpress site). 

Is it possible to reset these external ID values in Discourse? Or will I need to see about resetting them in WordPress to match the Discourse values?

**Comment by scossar** [comment]
The SSO external id is meant to be a value that is never changed: https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045 It seems to me that since your user ids have been changed, your forum's SSO records are no longer valid.

The easiest/safest thing to do might be to destroy the SSO records on your Discourse forum. If you do that, new SSO records will be created for your users when they first log in to the forum. Assuming that their Discourse email address and WordPress email match, they will be logged into their existing Discourse account. **Note: If their Discourse email and WordPress email do not match, a new Discourse account will be created based on the WordPress email.**

It might be a good idea to ask on the Discourse forum about destroying the SSO records.

I can give this a bit more thought and get back to you tomorrow.

**Comment by no2pixel** [comment]
Thanks for the explanation. I'll see what I can find out there.

**Comment by no2pixel** [comment]
@scossar -- Just to update this, deleting all of the sso records did indeed fix the issue.

For potential future users who land here looking for this answer, here is the thread on the Discourse meta forums - https://meta.discourse.org/t/resetting-or-destroying-single-sign-on-records/62619
