### ISSUE TITLE
Plugin is not working with several warnings

### ISSUE THREAD

**Issue by matthieu-lapeyre** [discourse/wp-discourse#85]
Hi,

I did not manage to make the plugin work on our wordpress 4.0.

I get several warnings, on a post page:
```console 
Warning: First parameter must either be an object or the name of an existing class in 
... /wp-content/plugins/wp-discourse-master/wp-discourse.php on line 410

Warning: file_get_contents(/wordpress.json?
best=5&min_trust_level=1&min_score=30&min_replies=1&bypass_trust_level_score=50) [function.file-
get-contents]: failed to open stream: No such file or directory in .../wp-content/plugins/wp-discourse-master/wp-discourse.php on line 195
```

And when I update a post after checking the discourse option:

```console
Warning: Cannot modify header information - headers already sent by (output started at
 .../wp-content/plugins/wp-discourse-master/wp-discourse.php:410) in
 .../wp-includes/pluggable.php on line 1173
```

**Comment by retlehs** [comment]
related: #83

**Comment by yyhmsg** [comment]
This is a similar I get on the latest wordpress with discourse running in a docker install.  I'm submitting this because it seems similar but with a slightly different error code and different line numbers, so felt it was worth noting.

This is upon submitting a new post - not sure if it ever gets to discourse or not. 

Warning: First parameter must either be an object or the name of an existing class in ../wp-content/plugins/wp-discourse-master/lib/discourse.php on line 468

Warning: Cannot modify header information - headers already sent by (output started at ../wp-content/plugins/wp-discourse-master/lib/discourse.php:468) in ../wp-admin/post.php on line 233

**Comment by retlehs** [comment]
this error is happening because there isn't really any error handling right now. double check all the plugin settings and try to submit/update a post again

example of a bad setting: using `discourse.example.com` instead of `http://discourse.example.com` as the discourse URL

**Comment by yyhmsg** [comment]
Thanks for the reply!  will do, I looked around for any extensive documentation - is there any that you can point me to?  It looks like the local install is setup correctly, but I'm not sure what I need on the server side - 
 - do you have to use the sso option if you don't want local wp accounts?
 - on the server side, do you need to fill out all of the embedding section?

I'm guessing that's where my error is, is the uncertainty about the embedding section server side...

**Comment by yyhmsg** [comment]
I still cannot get this working.  If anyone can comment on my settings I'd appreciate it:

URL:  http://community.yinyanghouse.com (I've also tried https://community.yinyanghouse.com (my actual url), community.yinyanghouse.com and all combinations with or without a trailing slash)

Publishing Username:  Chad_Dupuis
Published Category:  blog (also tried Blog as the desc is, but lowercase as the url is)

The rest seem easy enough and the error seems to still be about the url.  The error I get with the latest build is:
Warning: First parameter must either be an object or the name of an existing class in /home/xxx/public_html/wp-content/plugins/wp-discourse-master/wp-discourse.php on line 417

Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/wp-content/plugins/wp-discourse-master/wp-discourse.php:417) in /home/xxx/public_html/wp-admin/post.php on line 233

line 417 is:
     if( property_exists( $json, 'id' ) ) {
        $discourse_id = (int) $json->id;
      }

So I'm assuming either it isn't getting the post_id or the url is building an improper json call.  But I can't really debug much further.  Any help would be much appreciated.

**Comment by yyhmsg** [comment]
I figured it out, it was a firewall issue at the host level not letting the my main blog server communicate with the discourse instance which is on a different server.  Haven't tested much further but I did get a post to go through...  Sorry for all the noise....

**Comment by bsides** [comment]
@yyhmsg I'm sorry but how did you solve it?

**Comment by tnorthcutt** [comment]
@yyhmsg it probably makes sense to close this issue if it's resolved.

**Comment by yyhmsg** [comment]
@bsides Like my message says it was a firewall issue blocking the requests (my host fixed, since I've changed hosts and didn't have the problem on my current setup).  Even after resolving that, the plugin really didn't work well until the latest discourse versions (the last 4 or so).  Now it all just seems to work well.  Install discourse, install your blog, install the plugin and it should work.

closes #85

**Comment by bsides** [comment]
Thank you @yyhmsg :+1:

**Comment by retlehs** [comment]
issues like this should be easier debugged after #193 and #189
